# Generated by Django 3.2.4 on 2021-06-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_servicos_servico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipe',
            new_name='Funcionario',
        ),
    ]
